id: D0BEFAEFE
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-03-08T06:44:10+00:00'
last_modified: '2022-05-27T09:46:18.562823+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    2ee0:
      image_group_id: I1PD95905
      title: དབུ་མ་ལ་འཇུག་པ།
      total_pages: 1913
      order: 60
      base_file: 2ee0.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
